method to get a BER encoded tag's number
cunicu/go-iso7816 pull request #39
Opened 2024-10-11 20:45 UTC by OmegaRelay

Hello, this commit adds a method to get the tag number from a BER encoded tag, and modifies the tag test to include the new method.

Let me know what you think :)

2024-10-11 22:48 UTC, stv0g requested changes
Great addition 👍 I like it. What do you think about naming it just `Number()`? The tags number alone isn't BER specific, or is it?

It happens just that we use the BER encoding to for our internal representation for a Tag in a `uint`. We could also have used a struct, but decided for a unit as it's easier to declare a large set if tags as it happens in a lot of SmartCard applications.

2024-10-13 10:47 UTC, OmegaRelay commented
> Great addition 👍 I like it. What do you think about naming it just `Number()`? The tags number alone isn't BER specific, or is it?
> 
> It happens just that we use the BER encoding to for our internal representation for a Tag in a `uint`. We could also have used a struct, but decided for a unit as it's easier to declare a large set if tags as it happens in a lot of SmartCard applications.

Thanks for reviewing. 
I see the reason behind using the uint instead of a struct but the intention behind this method is to be able to get the tag number specifically for BER encoded tags where the tag also contains the class and constructed bits. This method does not work for simple or compact tlv tags and therefore I named it BERNumber to specify usage.

2024-10-14 02:08 UTC, stv0g approved these changes

2024-10-14 02:08 UTC, stv0g commented
I see. Thanks for your contribution :)

2024-10-14 02:09 UTC, merged